[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.23" # ^0.10 seems not compatible with current structure
spin = "0.9.4"
volatile = "0.2.7"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
